### ISSUE TITLE
WOSS multiple calls to Bellhop

### ISSUE THREAD

**Issue by biubiubiu238** [signetlabdei/WOSS#13]
When WOSS calls Bellhop to calculate data for multiple receiving points, why isn't it designed to make one Bellhop call to calculate multiple points (Bellhop itself supports multi-point calculation), but instead calls Bellhop once for each point? Is this done for performance considerations?

**Comment by MetalKnight** [comment]
@biubiubiu238 WOSS is using bellhop in 2D mode.
In this mode, bellhop supports a set of RX ranges and depth.
All of these ranges have to lie on the same 2D vertical plane that connects transmitting and receiving points.

Meaning, you can use mulitple combination of rx ranges and depth only if they are aligned.

This might happen in some specific static or grid spaces simulations (for some of the nodes), but it is not that frequent in dynamic simulations, hence the small performance savings on modern computers should not that much of a factor.
